version: '2.2'
services: 
 app: 
  image: docker-node-express-mongoapp
  restart: always
  build: .
  ports: 
    - '5000:3000'
  links:
    - mongo
mongo: 
  container_name: mongodatabase
  image: mongo
  ports:
    - '27018:27017'